apiVersion: 1
datasources:
  - name: PostgreSQL-ProStart
    type: postgres
    uid: PE02C6D58FFD076CD
    access: proxy
    url: db:5432
    user: grafana_reader
    secureJsonData:
      password: ${GRAFANA_READER_PASSWORD}
    jsonData:
      database: prostart
      sslmode: disable
      postgresVersion: 1700
      timescaledb: true
    isDefault: true
    editable: true
