apiVersion: 1

datasources:
  - name: PostgreSQL-ProStart
    type: postgres
    access: proxy
    isDefault: true
    editable: true
    database: prostart
    user: grafana_reader
    secureJsonData:
      password: 'Grafana@Dev2026'
    jsonData:
      sslmode: disable
      postgresVersion: 1700
      timescaledb: true
    url: db:5432
